# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27eb3307f20078c744624f61cfacb7c212e9d72fd0854e9e45ddfe165c5cd03b3863c03440ab4f73431b970cf409b6effe3e8818308ba0130602f8ef42cbd134
  stripe_public_key: pk_test_4Kx0Tt2mptU08EQi8RHUBVo9
  stripe_private_key: sk_test_Mq4AUIcFGhBS3wWxIavwtPDR

test:
  secret_key_base: b3d4ce7e5f1e5eba1a41920668d778a15f3fa69400b926a04c46af7e9bd3135f9145d687049aa2c55cbeda3901382161709a4875ced79ddf9cfe53b17bf8b21f
  stripe_public_key: pk_test_4Kx0Tt2mptU08EQi8RHUBVo9
  stripe_private_key: sk_test_Mq4AUIcFGhBS3wWxIavwtPDR

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_public_key: <%= ENV["STRIPE_PUBLIC_KEY"] %>
  stripe_private_key: <%= ENV["STRIPE_PRIVATE_KEY"] %>
